#!/usr/bin/python3
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import os
import sys

# import Cockpit's machinery for test VMs and its browser test API
TEST_DIR = os.path.dirname(__file__)
sys.path.append(os.path.join(TEST_DIR, "common"))
sys.path.append(os.path.join(os.path.dirname(TEST_DIR), "bots/machine"))
import testlib

# Nondestructive tests all run in the same running VM. This allows them to run in Packit, Fedora, and RHEL dist-git gating
# They must not permanently change any file or configuration on the system in a way that influences other tests.
@testlib.nondestructive
class TestNavigator(testlib.MachineCase):
    @classmethod
    def setUpClass(cls):
        # Run browser in UTC as the displayed time is in the browser's timezone
        os.environ['TZ'] = 'UTC'

    # FIXME: Move to testlib.py
    def select_PF5(self, b, selector_button: str, selector: str, value):
        b.click(f"{selector_button}:not([disabled]):not([aria-disabled=true])")
        select_entry = f"{selector} ul button:contains('{value}')"
        b.click(select_entry)

    def testBasic(self):
        b = self.browser
        m = self.machine

        self.restore_dir("/home/admin")

        self.login_and_go("/navigator")
        # expected heading
        b.wait_text("#navigator-card-header", "Directories & files")
        files_cnt = m.execute("ls -A /home/admin | wc -l").strip()
        hidden_files_cnt = m.execute('ls -A /home/admin | grep "^\." | wc -l').strip()
        b.wait_text("#sidebar-card-header", f"admin{files_cnt} items ({hidden_files_cnt} hidden)")

        # new files are auto-detected
        m.execute("touch --date @1641038400 /home/admin/newfile")
        b.wait_visible("[data-item='newfile']")

        # new directories are auto-detected
        m.execute("mkdir /home/admin/newdir; touch --date @1641038400 /home/admin/newfile /home/admin/newdir")
        b.wait_visible("[data-item='newdir']")

        # hidden files are not displayed
        m.execute("touch /home/admin/.hiddenfile /home/admin/not-hidden")
        b.wait_visible("[data-item='not-hidden']")
        b.wait_not_present("[data-item='.hiddenfile']")

        # file sidebar information
        b.click("button:contains('newfile')")
        b.wait_text("#sidebar-card-header", "newfile")
        b.wait_text("#description-list-owner dd", "root")
        b.wait_text("#description-list-group dd", "root")
        b.wait_text("#description-list-size dd", "0 B")
        b.wait_text("#description-list-last-modified dd", "Jan 1, 2022, 12:00 PM")

        # saving a file updates sidebar info
        # FIXME: Size does not update
        m.execute("head -c 7 /dev/zero > /home/admin/newfile")
        b.wait_text("#description-list-size dd", "7 B")
        b.wait_not_in_text("#description-list-last-modified ", "Jan 1, 2022, 12:00 PM")
        m.execute("touch --date @1641038400 /home/admin/newfile")
        b.wait_in_text("#description-list-last-modified ", "Jan 1, 2022, 12:00 PM")

        # clicking empty space resets sidebar
        b.click("#folder-view")
        b.wait_in_text("#sidebar-card-header", "admin")

        # folder information doesn't contain size
        b.click("button:contains('newdir')")
        b.wait_text("#sidebar-card-header", "newdir")
        b.wait_text("#description-list-owner dd", "root")
        b.wait_text("#description-list-group dd", "root")
        b.wait_not_present("#description-list-size")
        b.wait_text("#description-list-last-modified dd", "Jan 1, 2022, 12:00 PM")

        # filtering works
        self.browser.wait_js_cond("ph_count('#folder-view > button') > 1")
        b.set_input_text("input[placeholder='Filter directory']", "newfile")
        self.browser.wait_js_cond("ph_count('#folder-view > button') == 1")

        # filtering persists when changing view
        b.click("button[aria-label='Display as a list']")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') == 1")
        b.set_input_text("input[placeholder='Filter directory']", "")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') > 1")

        # deleted files and directories are auto-detected
        m.execute("rmdir /home/admin/newdir")
        m.execute("rm /home/admin/newfile")
        b.wait_not_present("[data-item='newdir']")
        b.wait_not_present("[data-item='newfile']")

        # current directory sidebar item count is updated
        files_cnt = m.execute("ls -A /home/admin | wc -l").strip()
        hidden_files_cnt = m.execute('ls -A /home/admin | grep "^\." | wc -l').strip()
        b.wait_text("#sidebar-card-header", f"admin{files_cnt} items ({hidden_files_cnt} hidden)")

        # sidebar is reset when files are removed
        b.wait_in_text("#sidebar-card-header", "admin")

    def testNavigation(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/navigator")

        b.wait_text(".breadcrumb-button:nth-of-type(1)", "/")
        b.wait_text(".breadcrumb-button:nth-of-type(2)", "home")
        b.wait_text(".last-breadcrumb-button", "admin")

        # clicking on the home button should take us to the home directory
        b.click(".breadcrumb-button:nth-of-type(2)")
        b.wait_not_present(".breadcrumb-button:nth-of-type(2)")
        b.wait_text(".last-breadcrumb-button", "home")
        b.wait_visible("[data-item='admin']")

        # show folder info in sidebar
        b.click("button:contains('admin')")
        b.wait_in_text("#sidebar-card-header", "admin")

        # double-clicking on a directory should take us into it
        b.mouse("[data-item='admin']", "dblclick")
        b.wait_not_present("[data-item='admin']")
        b.wait_text(".last-breadcrumb-button", "admin")

        # navigating into a directory resets the sidebar
        b.wait_in_text("#sidebar-card-header", "admin")

    def testSorting(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/navigator")

        # Expected heading
        b.wait_text("#navigator-card-header", "Directories & files")

        # Create test files and folders
        m.execute("touch -d '3 hours ago' /home/admin/aaa")
        b.wait_visible("[data-item='aaa']")
        m.execute("touch -d '4 hours ago' /home/admin/BBB")
        b.wait_visible("[data-item='BBB']")
        m.execute("touch -d '2 hours ago' /home/admin/ccc")
        b.wait_visible("[data-item='ccc']")

        # Sort by reverse alphabet
        self.select_PF5(b, "#sort-menu-toggle", "#sort-menu", "Z-A")
        # Alphabet sorts should be case insensetive
        b.wait_text(".item-button:nth-of-type(1)", "ccc")
        b.wait_text(".item-button:nth-of-type(2)", "BBB")
        b.wait_text(".item-button:nth-of-type(3)", "aaa")

        # Sort by last modified
        self.select_PF5(b, "#sort-menu-toggle", "#sort-menu", "Last modified")
        b.wait_text(".item-button:nth-of-type(1)", "ccc")
        b.wait_text(".item-button:nth-of-type(2)", "aaa")
        b.wait_text(".item-button:nth-of-type(3)", "BBB")

        # Update content of files
        m.execute('echo "update" > /home/admin/aaa')

        b.wait_text(".item-button:nth-of-type(1)", "aaa")
        b.wait_text(".item-button:nth-of-type(2)", "ccc")
        b.wait_text(".item-button:nth-of-type(3)", "BBB")

        # Sort by first modified
        self.select_PF5(b, "#sort-menu-toggle", "#sort-menu", "First modified")
        b.wait_text(".item-button:nth-of-type(1)", "BBB")
        b.wait_text(".item-button:nth-of-type(2)", "ccc")
        b.wait_text(".item-button:nth-of-type(3)", "aaa")

        # Sort by alphabet
        self.select_PF5(b, "#sort-menu-toggle", "#sort-menu", "A-Z")
        # Alphabet sorts should be case insensetive
        b.wait_text(".item-button:nth-of-type(1)", "aaa")
        b.wait_text(".item-button:nth-of-type(2)", "BBB")
        b.wait_text(".item-button:nth-of-type(3)", "ccc")

    def testDelete(self):
        b = self.browser
        m = self.machine

        self.login_and_go("/navigator")

        self.allow_journal_messages("rm: cannot remove '/home/admin/newdir/newfile': Permission denied",
                                    "rm: cannot remove '/home/admin/newfile': Operation not permitted")

        # Delete file
        m.execute("touch /home/admin/newfile")
        b.wait_visible("[data-item='newfile']")
        b.click("[data-item='newfile']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete file newfile?")
        b.click("button.pf-m-danger")
        b.wait_not_present("[data-item='newfile']")

        # Delete empty directory
        m.execute("mkdir /home/admin/newdir")
        b.wait_visible("[data-item='newdir']")
        b.click("[data-item='newdir']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete directory newdir?")
        b.click("button.pf-m-danger")
        b.wait_not_present("[data-item='newdir']")

        # Delete full directory
        m.execute("mkdir /home/admin/newdir")
        m.execute("touch /home/admin/newdir/newfile")
        b.wait_visible("[data-item='newdir']")
        b.click("[data-item='newdir']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete directory newdir?")
        b.click("button.pf-m-danger")
        b.wait_not_present("[data-item='newdir']")

        # Deleting protected file should give error
        m.execute("touch /home/admin/newfile")
        m.execute("sudo chattr +i /home/admin/newfile")
        b.wait_visible("[data-item='newfile']")
        b.click("[data-item='newfile']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete file newfile?")
        b.click("button.pf-m-danger")
        b.wait_in_text("h1.pf-c-modal-box__title", "Force delete file newfile?")
        b.wait_in_text("h4.pf-c-alert__title", "rm exited with code 1")
        b.click("button.pf-m-danger")
        b.wait_in_text("h1.pf-c-modal-box__title", "Force delete file newfile?")
        b.wait_in_text("h4.pf-c-alert__title", "rm exited with code 1")
        b.click("div.pf-c-modal-box__close")
        b.wait_visible("[data-item='newfile']")
        m.execute("sudo chattr -i /home/admin/newfile")
        b.click("[data-item='newfile']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete file newfile?")
        b.click("button.pf-m-danger")
        b.wait_not_present("[data-item='newfile']")

        # Delete current directory
        m.execute("mkdir /home/admin/newdir")
        b.wait_visible("[data-item='newdir']")
        b.mouse("[data-item='newdir']", "dblclick")
        b.wait_not_present("[data-item='newdir']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-c-modal-box__title", "Delete directory newdir?")
        b.click("button.pf-m-danger")
        b.wait_text(".last-breadcrumb-button", "admin")     
        b.wait_in_text("#sidebar-card-header", "admin")
        b.wait_not_present("[data-item='newdir']")

if __name__ == '__main__':
    testlib.test_main()
