#!/usr/bin/python3 -cimport os, sys; os.execv(os.path.dirname(sys.argv[1]) + "/common/pywrap", sys.argv)
# Run this with --help to see available options for tracing and debugging
# See https://github.com/cockpit-project/cockpit/blob/main/test/common/testlib.py
# "class Browser" and "class MachineCase" for the available API.

import datetime
import os
import re
import shlex
import subprocess
import tempfile
from pathlib import Path
from typing import List, Optional

# import Cockpit's machinery for test VMs and its browser test API
import testlib


# Nondestructive tests all run in the same running VM. This allows them to run
# in Packit, Fedora, and RHEL dist-git gating They must not permanently change
# any file or configuration on the system in a way that influences other tests.
@testlib.nondestructive
class TestFiles(testlib.MachineCase):
    @classmethod
    def setUpClass(_cls) -> None:
        # Run browser in UTC as the displayed time is in the browser's timezone
        os.environ['TZ'] = 'UTC'

    def setUp(self) -> None:  # type: ignore[override]
        super().setUp()
        self.restore_dir("/home/admin")

    def enter_files(self) -> None:
        self.login_and_go("/files")
        self.browser.wait_text(".pf-v5-c-empty-state__title-text", "Directory is empty")

    def stat(self, fmt: str, path: str) -> str:
        return self.machine.execute(['stat', f'--format={fmt}', path]).strip()

    def assert_stat(self, fmt: str, path: str, expected: str) -> None:
        self.assertEqual(self.stat(fmt, path), expected)

    def assert_owner(self, path: str, owner: str) -> None:
        self.assert_stat('%U:%G', path, owner)

    def assert_last_breadcrumb(self, directory: str) -> None:
        if directory == '/':
            self.browser.wait_visible("a.pf-v5-c-breadcrumb__link.pf-m-current svg.breadcrumb-hdd-icon")
        else:
            self.browser.wait_text(".pf-v5-c-page__main-breadcrumb a.pf-m-current", directory)

    def delete_item(self, filetype: str, filename: str, *, expect_success: bool = True) -> None:
        b = self.browser
        b.click(f"[data-item='{filename}']")
        b.click("#dropdown-menu")
        b.click("#delete-item")
        b.wait_in_text("h1.pf-v5-c-modal-box__title", f"Delete {filetype} {filename}?")
        b.click("button.pf-m-danger")
        if expect_success:
            b.wait_not_present(".pf-v5-c-modal-box")
            b.wait_not_present(f"[data-item='{filename}']")

    def create_directory(self, filename: str, owner: str | None = None, *, expect_success: bool = True) -> None:
        b = self.browser
        b.click("#dropdown-menu")
        b.click("#create-folder")
        b.set_input_text("#create-directory-input", f"{filename}")
        if owner:
            b.select_from_dropdown("#create-directory-owner", owner)
        b.click("button.pf-m-primary")
        if expect_success:
            b.wait_not_present(".pf-v5-c-modal-box")

    def wait_modal_inline_alert(self, msg: str) -> None:
        b = self.browser
        b.wait_in_text("h4.pf-v5-c-alert__title", msg)

    def rename_item(self, itemname: str, newname: str) -> None:
        b = self.browser
        b.click(f"[data-item='{itemname}']")
        b.click("#dropdown-menu")
        b.click("#rename-item")
        b.wait_in_text("h1.pf-v5-c-modal-box__title", "Rename")
        b.set_input_text("#rename-item-input", f"{newname}")
        b.click("button.pf-m-primary")

    def waitDownloadFile(self, filename: str, expected_size: int | None = None, content: str | None = None) -> None:
        b = self.browser
        filepath = b.driver.download_dir / filename

        # Big downloads can take a while
        testlib.wait(filepath.exists, tries=120)
        if expected_size is not None:
            testlib.wait(lambda: filepath.stat().st_size == expected_size)

        if content is not None:
            self.assertEqual(filepath.read_text(), content)

    def file_action_modal(self, filename: str, action: str) -> None:
        b = self.browser
        b.click(f"[data-item='{filename}']")
        b.click("#dropdown-menu")
        b.click(f"#dropdown-menu + .pf-v5-c-menu button:contains('{action}')")

    def open_folder_context_menu(self) -> None:
        # With BiDi on Firefox a click is by default in the "middle" of the
        # element while we want to open the current folder context and a
        # "middle" click can be a file or folder item.
        self.browser.mouse("#files-card-parent", "contextmenu", 1, 1)

    def testBasic(self) -> None:
        b = self.browser
        m = self.machine

        self.enter_files()

        b.allow_download()
        # expected heading
        b.wait_visible(".header-toolbar")

        # empty directory with one hidden file
        m.execute("runuser -u admin mkdir /home/admin/empty")
        m.execute("runuser -u admin touch /home/admin/empty/.hiddenfile")
        b.mouse("[data-item='empty']", "dblclick")
        b.wait_text(".pf-v5-c-empty-state__title-text", "Directory is empty")
        b.wait_in_text(".pf-v5-c-empty-state__body", "1 item is hidden")
        b.assert_pixels(".pf-v5-c-page__main", "empty-folder-view")

        # Clicking `show hidden items` shows it
        b.click(".pf-v5-c-empty-state button:contains('Show hidden items')")
        b.wait_visible("[data-item='.hiddenfile']")

        # Reset global setting
        b.select_PF("#sort-menu-toggle", "Hide hidden items")
        b.wait_not_present("[data-item='.hiddenfile']")
        b.wait_text(".pf-v5-c-empty-state__title-text", "Directory is empty")

        # removing the empty file shows empty directory again
        m.execute("rm /home/admin/empty/.hiddenfile")
        b.wait_text(".pf-v5-c-empty-state__title-text", "Directory is empty")
        b.wait_not_in_text(".pf-v5-c-empty-state", "1 item is hidden")

        b.click("li[data-location='/home/admin'] a")  # go back to home dir
        m.execute("rm -r /home/admin/empty")
        b.wait_not_present("[data-item='empty']")

        # new files are auto-detected
        m.execute("touch --date @1641038400 /home/admin/newfile")
        b.wait_visible("[data-item='newfile']")

        # new directories are auto-detected
        m.execute("mkdir /home/admin/newdir; touch --date @1641038400 /home/admin/newfile /home/admin/newdir")
        b.wait_visible("[data-item='newdir']")

        # hidden files are not displayed
        m.execute("touch /home/admin/.hiddenfile /home/admin/not-hidden")
        b.wait_visible("[data-item='not-hidden']")
        b.wait_not_present("[data-item='.hiddenfile']")

        # Symlink to `.` and `..` work and get shown as directories
        m.execute("ln -sf . /home/admin/dot")
        b.wait_visible("[data-item='dot'].symlink.folder")
        m.execute("ln -sf .. /home/admin/dotdot")
        b.wait_visible("[data-item='dotdot'].symlink.folder")

        b.assert_pixels("#files-card-parent", "folder-view")

        # filtering works
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') > 1")
        b.set_input_text("input[placeholder='Filter directory']", "newfile")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') == 1")

        # no results when filtering
        b.set_input_text("input[placeholder='Filter directory']", "absolutelynothing")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') == 0")
        b.wait_text(".pf-v5-c-empty-state__title-text", "No matching results")

        # clear using empty-state
        b.click(".pf-v5-c-empty-state button:contains('Clear filter')")
        b.wait_text("input[placeholder='Filter directory']", "")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') != 0")

        # clear using input button
        b.set_input_text("input[placeholder='Filter directory']", "absolutelynothing")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') == 0")
        b.wait_text(".pf-v5-c-empty-state__title-text", "No matching results")

        b.click("input[aria-label='Search input']")
        b.wait_text("input[placeholder='Filter directory']", "")

        # filtering persists when changing view
        b.click("button[aria-label='Display as a list']")
        b.set_input_text("input[placeholder='Filter directory']", "newfile")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') == 1")
        b.set_input_text("input[placeholder='Filter directory']", "")
        self.browser.wait_js_cond("ph_count('#folder-view tbody tr') > 1")

        # Big file downloads fine, runs in this test as running two downloads
        # in the same test causes issues with Chromium. This takes ~ 40 seconds.
        m.execute("truncate -s 1500M /home/admin/test.iso")
        b.wait_visible("[data-item='test.iso']")
        b.mouse("[data-item='test.iso']", "contextmenu")
        b.click(".contextMenu button:contains('Download')")
        self.waitDownloadFile("test.iso", 1500 * 1024 * 1024)

        # Selected view is saved in localStorage
        b.logout()
        self.login_and_go("/files")
        b.wait_visible("button[aria-label='Display as a grid']")

        # deleted files and directories are auto-detected
        m.execute("rmdir /home/admin/newdir")
        m.execute("rm /home/admin/newfile")
        b.wait_not_present("[data-item='newdir']")
        b.wait_not_present("[data-item='newfile']")

        # List root directory
        # Click "/" on the breadcrumb
        b.click("li[data-location='/'] a")  # go back to home dir
        b.wait_visible("[data-item='home']")

        # Enter /dev to make sure we can show special files properly
        b.mouse("[data-item='dev']", "dblclick")
        b.wait_visible("[data-item='urandom']")

        # Non-existing directory
        b.wait_visible("#dropdown-menu")
        b.go("/files#/?path=/doesnotexists")
        b.wait_in_text(".pf-v5-c-empty-state__body", "No such file or directory")
        b.wait_not_present("#dropdown-menu")

        # Path with multiple slashes is normalized
        b.go("/files#/?path=/////")
        b.wait_text("li[data-location='/']", "")

        # Path without a forward slash does get one
        b.go("/files#/?path=etc")
        b.wait_text("li[data-location='/etc']", "etc")

    def testPermissions(self) -> None:
        b = self.browser
        m = self.machine
        has_selinux = not any(img in m.image for img in ["arch", "debian", "ubuntu", "suse"])

        def select_access(access: str) -> None:
            b.select_from_dropdown("#edit-permissions-owner-access", access)
            b.select_from_dropdown("#edit-permissions-group-access", access)
            b.select_from_dropdown("#edit-permissions-other-access", access)

        def open_permissions_dialog(filename: str) -> None:
            b.wait_visible(f"[data-item='{filename}']")
            b.mouse(f"[data-item='{filename}']", "contextmenu")
            b.click(".contextMenu button:contains('Edit permissions')")
            b.wait_in_text(".pf-v5-c-modal-box__title-text", filename)

        def check_perms_match(filename: str, basedir: str) -> None:
            ls = m.execute(f"ls -l {basedir}/{filename}")[:10]
            # format ls output with spaces to match string in UI
            spaced_ls = f"{ls[1:4]} {ls[4:7]} {ls[7:10]}"
            b.wait_in_text(f"[data-item='{filename}'] .item-perms pre", spaced_ls)

        self.enter_files()

        b.click("button[aria-label='Display as a list']")

        # Check sidebar info
        m.execute("touch /home/admin/newfile")
        b.click("[data-item='newfile']")
        self.assertEqual(self.stat("%A", "/home/admin/newfile"), "-rw-r--r--")
        check_perms_match('newfile', '/home/admin')

        # Test changing owner/group
        m.execute("useradd testuser")
        open_permissions_dialog('newfile')
        b.assert_pixels(".pf-v5-c-modal-box", "permissions-modal")
        # Changing owner should change group if user is not in the group
        b.select_from_dropdown("#edit-permissions-owner", "testuser")
        b.wait_in_text("#edit-permissions-group", "testuser")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_in_text("[data-item='newfile'] .item-owner", "testuser")

        m.execute("usermod -a -G testuser admin")
        open_permissions_dialog('newfile')
        # Changing owner shouldn't change group if user is in the group
        b.select_from_dropdown("#edit-permissions-owner", "admin")
        b.wait_in_text("#edit-permissions-group", "testuser")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_in_text("[data-item='newfile'] .item-owner", "admin:testuser")

        # Change the group to admin
        open_permissions_dialog('newfile')
        b.select_from_dropdown("#edit-permissions-group", "admin")
        b.wait_in_text("#edit-permissions-group", "admin")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_in_text("[data-item='newfile'] .item-owner", "admin")

        # Test changing permissions
        open_permissions_dialog('newfile')
        select_access("no-access")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        self.assertEqual(self.stat("%A", "/home/admin/newfile"), "----------")
        check_perms_match('newfile', '/home/admin')

        open_permissions_dialog('newfile')
        select_access("read-write")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        self.assertEqual(self.stat("%A", "/home/admin/newfile"), "-rw-rw-rw-")
        check_perms_match('newfile', '/home/admin')

        # Test changing CWD permissions
        test_dir = "/home/admin/testdir"
        m.execute(['runuser', '-u', 'admin', 'mkdir', test_dir])
        b.mouse("[data-item='testdir']", "dblclick")
        b.wait_visible(".pf-v5-c-empty-state")
        self.assert_last_breadcrumb("testdir")

        # Via contextmenu
        b.mouse("#files-card-parent", "contextmenu")
        b.click(".contextMenu button:contains('Edit permissions')")
        b.wait_in_text(".pf-v5-c-modal-box__title-text", "testdir")
        b.select_from_dropdown("#edit-permissions-owner-access", "read-write")
        b.select_from_dropdown("#edit-permissions-group-access", "read-only")
        b.select_from_dropdown("#edit-permissions-other-access", "read-only")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")

        self.assertEqual(self.stat("%A", test_dir), "drwxr-xr-x")

        # Via kebab
        b.click("#dropdown-menu")
        b.click("button:contains('Edit permissions')")
        b.wait_in_text(".pf-v5-c-modal-box__title-text", "testdir")
        b.select_from_dropdown("#edit-permissions-owner-access", "read-only")
        b.select_from_dropdown("#edit-permissions-group-access", "no-access")
        b.select_from_dropdown("#edit-permissions-other-access", "no-access")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")

        self.assertEqual(self.stat("%A", test_dir), "dr-x------")

        # Can set a file as executable
        b.click("li[data-location='/home/admin'] a")
        self.assert_last_breadcrumb("admin")

        shell_script = "install.sh"
        m.execute(['runuser', '-u', 'admin', 'touch', f'/home/admin/{shell_script}'])
        m.execute(['chmod', '644', f'/home/admin/{shell_script}'])

        open_permissions_dialog(shell_script)
        b.wait_val("#edit-permissions-owner-access", "read-write")
        b.wait_val("#edit-permissions-group-access", "read-only")
        b.wait_val("#edit-permissions-other-access", "read-only")
        if has_selinux:
            b.wait_val("#selinux-context", "unconfined_u:object_r:user_home_t:s0")
        else:
            b.wait_not_present("#selinux-content")
        self.assertFalse(b.get_checked("#is-executable"))

        b.set_checked("#is-executable", True)
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")

        self.assertEqual(self.stat("%A", f"/home/admin/{shell_script}"), "-rwxr-xr-x")
        check_perms_match(shell_script, '/home/admin')

        open_permissions_dialog(shell_script)
        b.wait_in_text(".pf-v5-c-modal-box__title-text", shell_script)

        # Permissions did not change visually only executable is checked now
        b.wait_val("#edit-permissions-owner-access", "read-write")
        b.wait_val("#edit-permissions-group-access", "read-only")
        b.wait_val("#edit-permissions-other-access", "read-only")
        self.assertTrue(b.get_checked("#is-executable"))

        b.set_checked("#is-executable", False)
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")
        self.assertEqual(self.stat("%A", f"/home/admin/{shell_script}"), "-rw-r--r--")

        # Not executable for .png
        img_file = "cockpit.png"
        m.execute(['runuser', '-u', 'admin', 'touch', f'/home/admin/{img_file}'])

        open_permissions_dialog(img_file)
        b.wait_not_present("#is-executable")
        b.click("div.pf-v5-c-modal-box__close button")
        b.wait_not_present(".pf-v5-c-modal-box")

        # fifo not executable
        fifo_file = "test.fifo"
        m.execute(['runuser', '-u', 'admin', 'mkfifo', f'/home/admin/{fifo_file}'])

        open_permissions_dialog(fifo_file)
        b.wait_not_present("#is-executable")
        b.click("div.pf-v5-c-modal-box__close button")
        b.wait_not_present(".pf-v5-c-modal-box")

        # `uname` can be marked as executable
        executable_file = "uname"
        m.execute(['runuser', '-u', 'admin', 'touch', f'/home/admin/{executable_file}'])
        m.execute(['chmod', '644', f'/home/admin/{executable_file}'])

        open_permissions_dialog(executable_file)
        b.set_checked("#is-executable", True)
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")

        check_perms_match(executable_file, '/home/admin')

        # Special file access permission cases

        # We normally don't provide "write-only" as an option unless someone
        # has misconfigured their access permissions. Also verify that +x bits
        # are retained.
        m.execute(['chmod', '532', f'/home/admin/{shell_script}'])
        b.click(f"[data-item='{shell_script}']")
        check_perms_match(shell_script, '/home/admin')
        open_permissions_dialog(shell_script)

        b.wait_in_text(".pf-v5-c-modal-box__title-text", shell_script)
        b.wait_val("#edit-permissions-owner-access", "read-only")
        b.wait_val("#edit-permissions-group-access", "write-only")
        b.wait_val("#edit-permissions-other-access", "write-only")
        self.assertFalse(b.get_checked("#is-executable"))

        b.select_from_dropdown("#edit-permissions-group-access", "read-write")
        b.select_from_dropdown("#edit-permissions-other-access", "no-access")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")
        self.assertEqual(self.stat("%A", f"/home/admin/{shell_script}"), "-r-xrw----")

        b.go("/files#/?path=/")
        self.assert_last_breadcrumb("/")
        b.wait_not_present(".pf-v5-c-empty-state")

        # Shows / as /
        b.click("#dropdown-menu")
        b.click("#edit-permissions")
        b.wait_in_text(".pf-v5-c-modal-box__title-text", "/")
        b.click("button.pf-m-link")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Shows root user owns "bin"
        b.click("[data-item='bin']")
        b.click("#dropdown-menu")
        b.click("#edit-permissions")
        b.wait_in_text(".pf-v5-c-modal-box__title-text", "bin")
        b.wait_in_text("#edit-permissions-owner", "root")
        b.wait_in_text("#edit-permissions-group", "root")
        b.click("button.pf-m-link")
        b.wait_not_present(".pf-v5-c-modal-box")

        b.go("/files#/?path=/home/admin")
        self.assert_last_breadcrumb("admin")
        b.wait_not_present(".pf-v5-c-empty-state")

        # Enclosed folder permissions
        change_enclosed_dir = "/home/admin/Documents"
        create_test_dirs_sh = f"""
            mkdir {change_enclosed_dir}
            mkdir {change_enclosed_dir}/Finance
            mkdir {change_enclosed_dir}/Work
            chmod 750 {change_enclosed_dir}/Work
            touch {change_enclosed_dir}/Finance/program
            chmod 777 {change_enclosed_dir}/Finance/program
            touch {change_enclosed_dir}/Finance/accounts.txt
            chmod 600 {change_enclosed_dir}/Finance/accounts.txt
            touch {change_enclosed_dir}/Work/myvim
            chmod 750 {change_enclosed_dir}/Work/myvim
            touch {change_enclosed_dir}/Work/notes.txt
            chmod 644 {change_enclosed_dir}/Work/notes.txt
        """
        self.write_file("/usr/local/bin/create-test-dirs.sh", create_test_dirs_sh, perm="755")
        m.execute("runuser -u admin /usr/local/bin/create-test-dirs.sh")

        open_permissions_dialog("Documents")
        b.wait_val("#edit-permissions-owner-access", "read-write")
        b.wait_val("#edit-permissions-group-access", "read-only")
        b.wait_val("#edit-permissions-other-access", "read-only")
        b.click(".pf-v5-c-modal-box button.pf-m-secondary")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Files with any executable bit set, get a +x in all modes when +X is passed.
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance"), "drwxr-xr-x,admin,admin")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance/program"), "-rwxr-xr-x,admin,admin")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance/accounts.txt"), "-rw-r--r--,admin,admin")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work"), "drwxr-xr-x,admin,admin")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work/myvim"), "-rwxr-xr-x,admin,admin")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work/notes.txt"), "-rw-r--r--,admin,admin")

        # Via kebab it selects cwd
        b.mouse("[data-item='Documents']", "dblclick")
        b.wait_not_present(".pf-v5-c-empty-state")
        self.assert_last_breadcrumb("Documents")

        b.click("#dropdown-menu")
        b.click("button:contains('Edit permissions')")
        b.wait_in_text(".pf-v5-c-modal-box__title-text", "Documents")

        b.select_from_dropdown("#edit-permissions-group", "root")
        b.select_from_dropdown("#edit-permissions-owner-access", "read-only")
        b.select_from_dropdown("#edit-permissions-group-access", "no-access")
        b.select_from_dropdown("#edit-permissions-other-access", "no-access")
        b.click(".pf-v5-c-modal-box button.pf-m-secondary")
        b.wait_not_present(".pf-v5-c-modal-box")

        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance"), "dr-x------,admin,root")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance/program"), "-r-x------,admin,root")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Finance/accounts.txt"), "-r--------,admin,root")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work"), "dr-x------,admin,root")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work/myvim"), "-r-x------,admin,root")
        self.assertEqual(self.stat("%A,%U,%G",
                                   f"{change_enclosed_dir}/Work/notes.txt"), "-r--------,admin,root")

        b.click("li[data-location='/home/admin'] a")
        self.assert_last_breadcrumb("admin")

        # Edit multiple files
        create_multiple_dirs_sh = "mkdir -p /home/admin/multiple/testdir\n"
        for i in range(20):
            create_multiple_dirs_sh += f"touch /home/admin/multiple/filename{i}\n"

        self.write_file(f"{self.vm_tmpdir}/create-multiple-dirs.sh", create_multiple_dirs_sh, perm="755")
        m.execute(f"runuser -u admin {self.vm_tmpdir}/create-multiple-dirs.sh")
        b.mouse("[data-item='multiple']", "dblclick")
        b.wait_not_present(".pf-v5-c-empty-state")
        self.assert_last_breadcrumb("multiple")

        # Editing two files
        b.click("[data-item='filename1']")
        b.mouse("[data-item='filename2']", "click", ctrlKey=True)
        b.mouse("[data-item='filename1']", "contextmenu")
        b.click("button:contains('Edit permissions')")

        b.wait_text(".pf-v5-c-modal-box__title-text", "Permissions for 2 files")
        b.wait_in_text("#edit-permissions-owner", "admin")
        b.wait_in_text("#edit-permissions-group", "admin")
        b.select_from_dropdown("#edit-permissions-owner-access", "read-only")
        b.select_from_dropdown("#edit-permissions-group-access", "no-access")
        b.select_from_dropdown("#edit-permissions-other-access", "no-access")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        b.wait_not_present(".pf-v5-c-modal-box")
        self.assertEqual(self.stat("%A", "/home/admin/multiple/filename1"), "-r--------")
        self.assertEqual(self.stat("%A", "/home/admin/multiple/filename2"), "-r--------")

        # No owner/group shown if ownership differs
        def verify_no_owner_group_shown() -> None:
            # HACK: the selected state contains a copy of files state so permissions information is not updated.
            b.mouse("[data-item='filename1']", "click", ctrlKey=True)
            b.mouse("[data-item='filename1']", "click", ctrlKey=True)
            b.mouse("[data-item='filename1']", "contextmenu")
            b.click("button:contains('Edit permissions')")

            b.wait_visible("#edit-permissions-owner-access")
            b.wait_not_present("#edit-permissions-owner")
            b.wait_not_present("#edit-permissions-group")
            b.select_from_dropdown("#edit-permissions-owner-access", "read-write")
            b.select_from_dropdown("#edit-permissions-group-access", "read-only")
            b.select_from_dropdown("#edit-permissions-other-access", "read-only")

            b.click(".pf-v5-c-modal-box button.pf-m-primary")
            b.wait_not_present(".pf-v5-c-modal-box")

            self.assertEqual(self.stat("%A", "/home/admin/multiple/filename1"), "-rw-r--r--")
            self.assertEqual(self.stat("%A", "/home/admin/multiple/filename2"), "-rw-r--r--")

        m.execute("chmod 600 /home/admin/multiple/filename1")
        m.execute("chown root: /home/admin/multiple/filename1")
        b.wait_in_text("[data-item='filename1'] .item-owner", "root")
        verify_no_owner_group_shown()

        m.execute("chown admin:root /home/admin/multiple/filename1")
        b.wait_in_text("[data-item='filename1'] .item-owner", "admin:root")
        verify_no_owner_group_shown()

        # No Edit permissions when selecting a folder and files
        b.mouse("[data-item='testdir']", "click", ctrlKey=True)
        b.mouse("[data-item='filename1']", "contextmenu")
        b.wait_visible("button:contains('Delete')")
        b.wait_not_present("button:contains('Edit permissions')")

        # Editing > 10 files, select only files with the same owner/group
        # Test that we see an expander and can toggle it.
        b.mouse("[data-item='testdir']", "click", ctrlKey=True)
        b.mouse("[data-item='filename1']", "click", ctrlKey=True)
        for i in range(3, 15):
            b.mouse(f"[data-item='filename{i}']", "click", ctrlKey=True)

        b.mouse("[data-item='filename3']", "contextmenu")
        b.click("button:contains('Edit permissions')")

        b.wait_text(".pf-v5-c-modal-box__title-text", "Permissions for 13 files")
        b.assert_pixels(".pf-v5-c-modal-box", "multiple-files-permissions-modal")
        # Expand files
        b.wait_text(".pf-v5-c-expandable-section button", "Show all files")
        b.click(".pf-v5-c-expandable-section button")
        b.wait_text(".pf-v5-c-expandable-section button", "Collapse")
        b.click(".pf-v5-c-modal-box button.pf-m-link")
        b.wait_not_present(".pf-v5-c-modal-box")

        b.go("/files#/?path=/home/admin")
        self.assert_last_breadcrumb("admin")
        b.wait_not_present(".pf-v5-c-empty-state")

        # As normal user you cannot change user/group permissions
        b.drop_superuser()

        m.execute("touch /home/admin/adminfile; chown admin: /home/admin/adminfile")
        open_permissions_dialog('adminfile')
        select_access("read-write")
        # A user cannot change ownership
        b.wait_not_in_text(".pf-v5-c-modal-box__body", "Ownership")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        self.assertEqual(self.stat("%A", "/home/admin/adminfile"), "-rw-rw-rw-")
        check_perms_match('adminfile', '/home/admin')
        # Does not change ownership
        b.wait_in_text("[data-item='adminfile'] .item-owner", "admin")

        # Cannot change permission of /home
        b.click("li[data-location='/'] a")
        open_permissions_dialog('home')
        select_access("read-only")
        if has_selinux:
            b.wait_val("#selinux-context", "system_u:object_r:home_root_t:s0")
        b.click(".pf-v5-c-modal-box button.pf-m-primary")
        self.wait_modal_inline_alert("chmod: changing permissions of '/home': Operation not permitted")
        b.click(".pf-v5-c-modal-box button.pf-m-link")
        b.wait_not_present(".pf-v5-c-modal-box")

        b.go("/files#/?path=/home/admin")
        self.assert_last_breadcrumb("admin")
        b.wait_not_present(".pf-v5-c-empty-state")

        # Test error conditions in "change enclosing file permissions"
        m.execute("chattr +i /home/admin/Documents/Work/notes.txt")
        self.addCleanup(m.execute, "chattr -i /home/admin/Documents/Work/notes.txt")
        open_permissions_dialog("Documents")
        b.click(".pf-v5-c-modal-box button.pf-m-secondary")
        self.wait_modal_inline_alert("Operation not permitted")
        b.click("button.pf-m-link")
        b.wait_not_present(".pf-v5-c-modal-box")

        # Test permissions in details view
        basedir = "/home/admin"
        for i in range(8):
            m.execute(f"runuser -u admin touch {basedir}/file{i}")

        # Simple permissions
        m.execute(f"""
        chmod 000 {basedir}/file0
        chmod 111 {basedir}/file1
        chmod 222 {basedir}/file2
        chmod 333 {basedir}/file3
        chmod 444 {basedir}/file4
        chmod 555 {basedir}/file5
        chmod 666 {basedir}/file6
        chmod 777 {basedir}/file7
        """)

        b.mouse("[data-item='file6'] .item-perms pre", "mouseenter")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(1)", "read and write")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(2)", "read and write")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(3)", "read and write")
        b.mouse("[data-item='file6'] .item-perms pre", "mouseleave")

        for i in range(8):
            check_perms_match(f"file{i}", basedir)

        # Test different permissions for owner/group/others
        m.execute(f"""
        chmod 411 {basedir}/file0
        chmod 546 {basedir}/file1
        chmod 337 {basedir}/file2
        chmod 755 {basedir}/file3
        chmod 613 {basedir}/file4
        chmod 711 {basedir}/file5
        chmod 531 {basedir}/file6
        chmod 740 {basedir}/file7
        """)

        b.mouse("[data-item='file4'] .item-perms pre", "mouseenter")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(1)", "read and write")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(2)", "execute-only")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(3)", "write and execute")
        b.assert_pixels(".pf-v5-c-page__main", "permissions-tooltip", mock={".item-date": "Jun 19, 2024, 11:30 AM"})
        b.mouse("[data-item='file4'] .item-perms pre", "mouseleave")

        for i in range(8):
            check_perms_match(f"file{i}", basedir)

        # Test permissions with setuid, setgid, sticky
        m.execute(f"""
        chmod 1000 {basedir}/file0
        chmod 2111 {basedir}/file1
        chmod 3222 {basedir}/file2
        chmod 4333 {basedir}/file3
        chmod 5444 {basedir}/file4
        chmod 6555 {basedir}/file5
        chmod 7666 {basedir}/file6
        chmod 3777 {basedir}/file7
        """)

        b.mouse("[data-item='file7'] .item-perms pre", "mouseenter")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(1)", "read, write, and execute")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(2)", "read, write, and execute")
        b.wait_in_text(".pf-v5-c-tooltip dd:nth-of-type(3)", "read, write, and execute")
        b.mouse("[data-item='file7'] .item-perms pre", "mouseleave")

        for i in range(8):
            check_perms_match(f"file{i}", basedir)


if __name__ == '__main__':
    testlib.test_main()
