# Enable RPM builds and running integration tests in PRs through https://packit.dev/
# To use this, enable Packit-as-a-service in GitHub: https://packit.dev/docs/packit-as-a-service/
# See https://packit.dev/docs/configuration/ for the format of this file

specfile_path: cockpit-files.spec
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
  - make
  - nodejs-npm

actions:
  post-upstream-clone:
    - make cockpit-files.spec
    # replace Source1 manually, as create-archive: can't handle multiple tarballs
    - make node-cache
    - sh -c 'sed -i "/^Source1:/ s/https:.*/$(ls *-node*.tar.xz)/" cockpit-*.spec'
  create-archive: make dist
  # files.git has no release tags; your project can drop this once you have a release
  get-current-version: make print-version

jobs:
  - job: copr_build
    trigger: pull_request
    # implicitly defined by "tests" job, no extra build-only targets
    targets: []

  - job: tests
    trigger: pull_request
    targets:
      - fedora-41
      - fedora-42
      - fedora-development
      - fedora-latest-stable-aarch64
      - centos-stream-9-x86_64
      - centos-stream-10

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@cockpit"
    project: "main-builds"
    preserve_project: True

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make cockpit-files.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/cockpit-files/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@cockpit"
    project: "main-builds"
    preserve_project: True

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-41
      - fedora-42
      - fedora-development

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-41
      - fedora-42
      - fedora-development

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-41
      - fedora-42
