# Enable RPM builds and running integration tests in PRs through https://packit.dev/
# To use this, enable Packit-as-a-service in GitHub: https://packit.dev/docs/packit-as-a-service/
# See https://packit.dev/docs/configuration/ for the format of this file

upstream_project_url: https://github.com/cockpit-project/cockpit-files
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/cockpit-files
upstream_package_name: cockpit-files
downstream_package_name: cockpit-files
specfile_path: cockpit-files.spec
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

srpm_build_deps:
  - jq
  - make
  - nodejs

actions:
  post-upstream-clone:
    - make node-cache dist

  fix-spec-file:
    # our locally built tarballs are not on the upstream releases page, point to the local files
    sed -i 's|^\(Source[0-9]*:\s*\).*\/|\1|' cockpit-files.spec

jobs:
  - job: tests
    trigger: pull_request
    targets: &test_targets
      - centos-stream-9-x86_64
      - centos-stream-10

  - job: copr_build
    trigger: pull_request
    targets: *test_targets
